//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteJuegos.ServicioJuegos {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDificultad", Namespace="http://schemas.datacontract.org/2004/07/Gestor_Juegos")]
    public enum TipoDificultad : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VACIO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MUY_FACIL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FACIL = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MEDIA = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DIFICIL = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MUY_DIFICIL = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioJuegos.IGestor_Juegos")]
    public interface IGestor_Juegos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/NuevoJuego", ReplyAction="http://tempuri.org/IGestor_Juegos/NuevoJuegoResponse")]
        int NuevoJuego(ClienteJuegos.ServicioJuegos.TipoDificultad pDifi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/NuevoJuego", ReplyAction="http://tempuri.org/IGestor_Juegos/NuevoJuegoResponse")]
        System.Threading.Tasks.Task<int> NuevoJuegoAsync(ClienteJuegos.ServicioJuegos.TipoDificultad pDifi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/BorrarJuego", ReplyAction="http://tempuri.org/IGestor_Juegos/BorrarJuegoResponse")]
        bool BorrarJuego(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/BorrarJuego", ReplyAction="http://tempuri.org/IGestor_Juegos/BorrarJuegoResponse")]
        System.Threading.Tasks.Task<bool> BorrarJuegoAsync(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/PonerValor", ReplyAction="http://tempuri.org/IGestor_Juegos/PonerValorResponse")]
        bool PonerValor(int pCodJuego, int pFila, int pColumna, char pValor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/PonerValor", ReplyAction="http://tempuri.org/IGestor_Juegos/PonerValorResponse")]
        System.Threading.Tasks.Task<bool> PonerValorAsync(int pCodJuego, int pFila, int pColumna, char pValor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/ObtenerValor", ReplyAction="http://tempuri.org/IGestor_Juegos/ObtenerValorResponse")]
        char ObtenerValor(int pCodJuego, int pFila, int pColumna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/ObtenerValor", ReplyAction="http://tempuri.org/IGestor_Juegos/ObtenerValorResponse")]
        System.Threading.Tasks.Task<char> ObtenerValorAsync(int pCodJuego, int pFila, int pColumna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/ComprobarValor", ReplyAction="http://tempuri.org/IGestor_Juegos/ComprobarValorResponse")]
        bool ComprobarValor(int pCodJuego, int pFila, int pColumna, char pValor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/ComprobarValor", ReplyAction="http://tempuri.org/IGestor_Juegos/ComprobarValorResponse")]
        System.Threading.Tasks.Task<bool> ComprobarValorAsync(int pCodJuego, int pFila, int pColumna, char pValor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/NumeroHuecos", ReplyAction="http://tempuri.org/IGestor_Juegos/NumeroHuecosResponse")]
        int NumeroHuecos(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/NumeroHuecos", ReplyAction="http://tempuri.org/IGestor_Juegos/NumeroHuecosResponse")]
        System.Threading.Tasks.Task<int> NumeroHuecosAsync(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/Ayuda", ReplyAction="http://tempuri.org/IGestor_Juegos/AyudaResponse")]
        string Ayuda(int pCodJuego, int pFila, int pColumna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/Ayuda", ReplyAction="http://tempuri.org/IGestor_Juegos/AyudaResponse")]
        System.Threading.Tasks.Task<string> AyudaAsync(int pCodJuego, int pFila, int pColumna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/Correcto", ReplyAction="http://tempuri.org/IGestor_Juegos/CorrectoResponse")]
        bool Correcto(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/Correcto", ReplyAction="http://tempuri.org/IGestor_Juegos/CorrectoResponse")]
        System.Threading.Tasks.Task<bool> CorrectoAsync(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/GetSudoku", ReplyAction="http://tempuri.org/IGestor_Juegos/GetSudokuResponse")]
        string GetSudoku(int pCodJuego);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestor_Juegos/GetSudoku", ReplyAction="http://tempuri.org/IGestor_Juegos/GetSudokuResponse")]
        System.Threading.Tasks.Task<string> GetSudokuAsync(int pCodJuego);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestor_JuegosChannel : ClienteJuegos.ServicioJuegos.IGestor_Juegos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Gestor_JuegosClient : System.ServiceModel.ClientBase<ClienteJuegos.ServicioJuegos.IGestor_Juegos>, ClienteJuegos.ServicioJuegos.IGestor_Juegos {
        
        public Gestor_JuegosClient() {
        }
        
        public Gestor_JuegosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Gestor_JuegosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Gestor_JuegosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Gestor_JuegosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int NuevoJuego(ClienteJuegos.ServicioJuegos.TipoDificultad pDifi) {
            return base.Channel.NuevoJuego(pDifi);
        }
        
        public System.Threading.Tasks.Task<int> NuevoJuegoAsync(ClienteJuegos.ServicioJuegos.TipoDificultad pDifi) {
            return base.Channel.NuevoJuegoAsync(pDifi);
        }
        
        public bool BorrarJuego(int pCodJuego) {
            return base.Channel.BorrarJuego(pCodJuego);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarJuegoAsync(int pCodJuego) {
            return base.Channel.BorrarJuegoAsync(pCodJuego);
        }
        
        public bool PonerValor(int pCodJuego, int pFila, int pColumna, char pValor) {
            return base.Channel.PonerValor(pCodJuego, pFila, pColumna, pValor);
        }
        
        public System.Threading.Tasks.Task<bool> PonerValorAsync(int pCodJuego, int pFila, int pColumna, char pValor) {
            return base.Channel.PonerValorAsync(pCodJuego, pFila, pColumna, pValor);
        }
        
        public char ObtenerValor(int pCodJuego, int pFila, int pColumna) {
            return base.Channel.ObtenerValor(pCodJuego, pFila, pColumna);
        }
        
        public System.Threading.Tasks.Task<char> ObtenerValorAsync(int pCodJuego, int pFila, int pColumna) {
            return base.Channel.ObtenerValorAsync(pCodJuego, pFila, pColumna);
        }
        
        public bool ComprobarValor(int pCodJuego, int pFila, int pColumna, char pValor) {
            return base.Channel.ComprobarValor(pCodJuego, pFila, pColumna, pValor);
        }
        
        public System.Threading.Tasks.Task<bool> ComprobarValorAsync(int pCodJuego, int pFila, int pColumna, char pValor) {
            return base.Channel.ComprobarValorAsync(pCodJuego, pFila, pColumna, pValor);
        }
        
        public int NumeroHuecos(int pCodJuego) {
            return base.Channel.NumeroHuecos(pCodJuego);
        }
        
        public System.Threading.Tasks.Task<int> NumeroHuecosAsync(int pCodJuego) {
            return base.Channel.NumeroHuecosAsync(pCodJuego);
        }
        
        public string Ayuda(int pCodJuego, int pFila, int pColumna) {
            return base.Channel.Ayuda(pCodJuego, pFila, pColumna);
        }
        
        public System.Threading.Tasks.Task<string> AyudaAsync(int pCodJuego, int pFila, int pColumna) {
            return base.Channel.AyudaAsync(pCodJuego, pFila, pColumna);
        }
        
        public bool Correcto(int pCodJuego) {
            return base.Channel.Correcto(pCodJuego);
        }
        
        public System.Threading.Tasks.Task<bool> CorrectoAsync(int pCodJuego) {
            return base.Channel.CorrectoAsync(pCodJuego);
        }
        
        public string GetSudoku(int pCodJuego) {
            return base.Channel.GetSudoku(pCodJuego);
        }
        
        public System.Threading.Tasks.Task<string> GetSudokuAsync(int pCodJuego) {
            return base.Channel.GetSudokuAsync(pCodJuego);
        }
    }
}
