/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorJuegos.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

#define cls system("clear")
#define pause system("read -p 'Pulsa return para continuar...  '  a")

typedef struct {
	int Codigo; 	        //Código del juego
	char Tablero[9][9];     //Tablero del juego
	enum TDificultad Dificultad; //Dificultad
} TJuego;


int MenuPrincipal(bool pInicio)
{
    int valor;

    if (pInicio)
    {
        printf("1.- Juego Nuevo\n");
        printf("2.- -----------\n");
        printf("3.- -----------\n");
        printf("4.- -----------\n");
        printf("5.- -----------\n");
    }
    else
    {
        printf("1.- -----------\n");
        printf("2.- Borrar Juego\n");
        printf("3.- Poner Valor\n");
        printf("4.- Borrar Valor\n");
        printf("5.- Ayuda\n");
    }
    printf("6.- Salir\n");
    printf("Elige Opción: ");
    scanf("%d",&valor);

    return valor;
}

TDificultad MenuDificultad()
{
    int valor=0;
    do
    {
        printf("Elija la Dificultad:\n");
        printf("Muy Fácil(1) Fácil(2) Medio(3) Difícil(4) Muy Difícil(5)\n");
        printf("Elige Opción: ");
        scanf("%d",&valor);
        if (valor<1 || valor>5)
            printf("** Error, elija una dificultad correcta.\n");
    }
    while(valor<1 || valor>5);
    return (TDificultad)valor;
}


void
gestorjuegos_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	TDificultad  nuevo_1_arg;
	bool_t  *result_2;
	int  borrar_1_arg;
	bool_t  *result_3;
	TFCV  ponervalor_1_arg;
	char  *result_4;
	TFC  obtenervalor_1_arg;
	bool_t  *result_5;
	TFCV  comprobarvalor_1_arg;
	int  *result_6;
	int  numerohuecos_1_arg;
	bool_t  *result_7;
	int  correcto_1_arg;
	RCadena  *result_8;
	TFC  ayuda_1_arg;
	RCadena  *result_9;
	int  getsudoku_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GESTORJUEGOS, GESTORJUEGOS_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = nuevo_1(&nuevo_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = borrar_1(&borrar_1_arg, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = ponervalor_1(&ponervalor_1_arg, clnt);
	if (result_3 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = obtenervalor_1(&obtenervalor_1_arg, clnt);
	if (result_4 == (char *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = comprobarvalor_1(&comprobarvalor_1_arg, clnt);
	if (result_5 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = numerohuecos_1(&numerohuecos_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = correcto_1(&correcto_1_arg, clnt);
	if (result_7 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = ayuda_1(&ayuda_1_arg, clnt);
	if (result_8 == (RCadena *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = getsudoku_1(&getsudoku_1_arg, clnt);
	if (result_9 == (RCadena *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	CLIENT *clnt;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	clnt = clnt_create (host, GESTORJUEGOS, GESTORJUEGOS_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	//gestorjuegos_1 (host);
	
	bool inicio = true;
	int *result, *result_borrar;
	int opcion, sn, aviso, F, C, Valor, sudoActual;
	char V;
	 
	TDificultad dif;
	TFCV *estructuraTFCV = (TFCV*) malloc (sizeof(TFCV));
	TFC *estructuraTFC = (TFC*) malloc (sizeof(TFC));
	
	RCadena *result2, *ayuda;
	
    	printf("Cliente: Tengo Conexión con el servidor comenzamos\n\n");
		

	do
	{
		cls;
		result2 = getsudoku_1(&sudoActual, clnt);
        	printf("%s\n",result2->Contenido);
        	if (aviso>0)
        	{
            		printf("*** \n");
            		switch (aviso)
            		{
            		case 1:
                		printf("La opción: %d no está en el menú.", opcion);
               			break;
            		case 2:
                		printf("La posición F=%d C=%d introducida es incorrecta.\n", F,C);
                		break;
            		case 3:
                		printf("La posición F=%d C=%d está ocupada.\n", F, C);
                		break;
            		case 4:
                		printf("El valor:%c no se puede poner en la posición F=%d C=%d\n", V,F,C);
                		break;
            		case 5:
                		printf("El valor:%c es incorrecto para el juego\n", V);
                		break;
            		case 6:
                		printf("Los posibles valores en la posición F=%d C=%d son: %s\n", F,C,ayuda->Contenido);
                		break;
			}
			printf(" ***\n");
            		aviso=0;
            	}
            	
        	if (numerohuecos_1(&sudoActual, clnt) == 0)
        	{	
            		printf("*** SUDOKU COMPLETO\n");
            		if (correcto_1(&sudoActual, clnt)==false)
                		printf("SUDOKU MAL COMPLETADO\n");
			else
            			printf("CORRECTO ***\n");
        	}

        	printf("\n");

						
		opcion = MenuPrincipal(inicio);
		printf("Valor devuelto por MenuPrincipal: %d\n", opcion);

		switch (opcion)
		{
			case 1: 
				printf("Ha seleccionado la opción 1.\n");	
				if (inicio == true) {
					cls;
					dif = (TDificultad) MenuDificultad();	
					result = nuevo_1(&dif, clnt);
					printf("El valor de result es: %d.\n", *result);
					if (result == (int *) NULL) {
						clnt_perror (clnt, "call failed");
					}
					inicio = false;
					sudoActual = *result;	
				}
				else aviso=1;		
				break;
			case 2: 
				printf("Ha seleccionado la opción 2.\n");
				if (inicio==false)
            			{		
                			printf("¿Está seguro de borrar el juego? (1/0): ");
                			scanf("%d",&sn);
                			if (sn== 1)
                			{
                    				result_borrar = borrar_1(&sudoActual, clnt);
						if (result_borrar == (bool_t *) NULL) {
							clnt_perror (clnt, "call failed");
						}
                    				inicio=true;
                			}
            			}
            			else aviso=1;
            			break;
			case 3: 
				printf("Ha seleccionado la opción 3.\n");
				if (inicio==false)
            			{
                			printf("Introduce Fila: ");
                			scanf("%d",&F);			
					
					printf("Introduce Columna y Valor: ");
					scanf("%d%d",&C, &Valor);

					V = Valor + '0';		
					
					estructuraTFCV->pCod = *result;
					estructuraTFCV->pFil = F;
					estructuraTFCV->pCol = C;
					estructuraTFCV->pVal = V;

					estructuraTFC->pCod = *result;
					estructuraTFC->pFil = F-1;
					estructuraTFC->pCol = C-1;

					printf("\n");
                			if (V<'1' || V>'9')
                    				aviso=5;
                			else if (F<1 || F>9 || C<1 || C>9 )
                    				aviso=2;
                			else if (*obtenervalor_1(estructuraTFC, clnt) != ' ')
                    				aviso=3;
                			else
                			{
						estructuraTFCV->pFil = F-1;
						estructuraTFCV->pCol = C-1;
						estructuraTFCV->pVal = V;
                    				ponervalor_1(estructuraTFCV, clnt);
                    				if (comprobarvalor_1(estructuraTFCV, clnt)==false)
                        				aviso=4;
                    				else
                        				aviso=0;
                			}
            			}
            			else aviso=1;
            			break;
			case 4: 
				if (inicio==false)
            			{
                			printf("Introduce Fila y Columna: ");
                			scanf("%d%d",&F,&C);
                			if (F<1 || F>9 || C<1 || C>9 )
                    				aviso=2;
                			else {
						estructuraTFCV->pFil = F-1;
						estructuraTFCV->pCol = C-1;
						estructuraTFCV->pVal = ' ';
						estructuraTFCV->pCod = *result;
						ponervalor_1(estructuraTFCV, clnt);
					}     				
            			}
            			else aviso=1;
				break;
			case 5:  
				if (inicio==false)
            			{
                			printf("Introduce Fila y Columna a obtener ayuda: ");
                			scanf("%d%d",&F,&C);
					
					estructuraTFC->pFil = F-1;
					estructuraTFC->pCol = C-1;
					estructuraTFC->pCod = *result;					

                			if (F<1 || F>9 || C<1 || C>9 || *obtenervalor_1(estructuraTFC, clnt) != ' ')
                    				aviso=2;
                			else
                			{
                    				ayuda = ayuda_1(estructuraTFC, clnt);
						//printf("El contenido de ayuda es: \n%s", ayuda->Contenido);
                    				aviso=6;
                			}
            			}
            			else aviso=1;
				break;
			case 6: 
				break;
			default: aviso=1;
		}
		
			
	} while(opcion!=6);	
    	printf("Cliente: Hemos terminado. Hasta otra\n\n");
	free(estructuraTFCV);
	free(estructuraTFC);
	clnt_destroy (clnt);
	
	exit (0);
}
